import type { GenderCode } from '../../enums/genderCode';
import type { PhysicalAddressDto } from '../physicalAddressDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.831Z
 * Do not edit this file manually
 */

export interface ApplicationUserDto {
  id: string;
  userName: string;
  email: string;
  firstName: string;
  middleName: string;
  lastName: string;
  phoneNumber: string | null;
  gender: GenderCode | null;
  bio: string | null;
  dateOfBirth: string | null;
  age: number;
  avatar: string | null;
  coverImageUrl: string | null;
  isVerified: boolean;
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string | null;
  discriminator: string | null;
  physicalAddressId: string | null;
  physicalAddress: PhysicalAddressDto | null;
}
