/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.842Z
 * Do not edit this file manually
 */

export interface PasswordResetVerificationResponseDto {
  email: string;
  passwordResetToken: string;
}
