/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.841Z
 * Do not edit this file manually
 */

export interface PasswordResetVerificationDto {
  userName: string;
  token: string | null;
  otp: string | null;
  returnUrl: string | null;
}
