/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.840Z
 * Do not edit this file manually
 */

export interface PasswordResetDto {
  email: string;
  token: string;
  oldPassword: string | null;
  newPassword: string;
  newPasswordConfirmation: string;
}
