/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.865Z
 * Do not edit this file manually
 */

export enum ApiActionMethodCode {
  Create = 'Create',
  Read = 'Read',
  Update = 'Update',
  Delete = 'Delete'
}
