/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.866Z
 * Do not edit this file manually
 */

export enum BillingCycleCode {
  None = 'None',
  Monthly = 'Monthly',
  Yearly = 'Yearly'
}
