/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.868Z
 * Do not edit this file manually
 */

export enum CompetitionStatusCode {
  Upcoming = 'Upcoming',
  Active = 'Active',
  Complete = 'Complete'
}
