/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.870Z
 * Do not edit this file manually
 */

export enum CupRoundBracketSideCode {
  Left = 'Left',
  Right = 'Right',
  Center = 'Center'
}
