/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.871Z
 * Do not edit this file manually
 */

export enum EventPostType {
  Public = 'Public',
  Private = 'Private',
  Workshop = 'Workshop',
  Conference = 'Conference',
  Meetup = 'Meetup',
  Webinar = 'Webinar',
  Party = 'Party',
  Concert = 'Concert',
  Sports = 'Sports',
  Festival = 'Festival',
  Fundraiser = 'Fundraiser',
  Networking = 'Networking',
  Training = 'Training',
  Seminar = 'Seminar',
  Exhibition = 'Exhibition',
  Competition = 'Competition',
  Social = 'Social',
  Corporate = 'Corporate',
  Community = 'Community',
  Educational = 'Educational',
  Other = 'Other'
}
