/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.871Z
 * Do not edit this file manually
 */

export enum FederationMembershipStatus {
  Pending = 'Pending',
  Active = 'Active',
  Rejected = 'Rejected',
  Suspended = 'Suspended'
}
