/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.873Z
 * Do not edit this file manually
 */

export enum JurisdictionLevelCode {
  Local = 'Local',
  Provincial = 'Provincial',
  International = 'International'
}
