/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.874Z
 * Do not edit this file manually
 */

export enum LineUpPlayerLinkStatusCode {
  StartingXI = 'StartingXI',
  Substitute = 'Substitute'
}
