/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.874Z
 * Do not edit this file manually
 */

export enum MatchEventCode {
  BallOutOfPlay = 'BallOutOfPlay',
  CardAwarded = 'CardAwarded',
  ExtraTimeEnded = 'ExtraTimeEnded',
  ExtraTimeStarted = 'ExtraTimeStarted',
  Foul = 'Foul',
  FullTime = 'FullTime',
  Goal = 'Goal',
  HalfTime = 'HalfTime',
  HalfTimeEnded = 'HalfTimeEnded',
  HalfTimeStarted = 'HalfTimeStarted',
  Injury = 'Injury',
  KickOff = 'KickOff',
  MatchStarted = 'MatchStarted',
  MatchEnded = 'MatchEnded',
  Offside = 'Offside',
  PenaltyAwarded = 'PenaltyAwarded',
  PenaltyShootoutStarted = 'PenaltyShootoutStarted',
  PenaltyShootoutEnded = 'PenaltyShootoutEnded',
  SetPiece = 'SetPiece',
  TimeExpired = 'TimeExpired',
  TimeAdded = 'TimeAdded',
  WaterBreakEnded = 'WaterBreakEnded',
  WaterBreakStarted = 'WaterBreakStarted'
}

export enum CardAwardedCode {
  RedCard = 'RedCard',
  YellowCard = 'YellowCard'
}

export enum SetPieceCode {
  DirectSetPiece = 'DirectSetPiece',
  IndirectSetPiece = 'IndirectSetPiece'
}

export enum DirectSetPieceCode {
  CornerKick = 'CornerKick',
  FreeKick = 'FreeKick',
  PenaltyKick = 'PenaltyKick'
}

export enum IndirectSetPieceCode {
  DropBall = 'DropBall',
  FreeKick = 'FreeKick',
  GoalKick = 'GoalKick',
  ThrowIn = 'ThrowIn'
}
