/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.875Z
 * Do not edit this file manually
 */

export enum MediaContext {
  Avatar = 'Avatar',
  Banner = 'Banner',
  Cover = 'Cover',
  Logo = 'Logo',
  Post = 'Post',
  Poll = 'Poll',
  Badge = 'Badge'
}
