/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.875Z
 * Do not edit this file manually
 */

export enum MediaTypeCode {
  Image = 'Image',
  Video = 'Video',
  Audio = 'Audio',
  Other = 'Other'
}
