/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.877Z
 * Do not edit this file manually
 */

export enum PlayerPositionGroupCode {
  GK = 'GK',
  DEF = 'DEF',
  MID = 'MID',
  ATT = 'ATT'
}
