/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.876Z
 * Do not edit this file manually
 */

export enum PlayerPositionCode {
  GK = 'GK',
  RB = 'RB',
  LB = 'LB',
  CB = 'CB',
  SW = 'SW',
  RWB = 'RWB',
  LWB = 'LWB',
  CDM = 'CDM',
  CM = 'CM',
  CAM = 'CAM',
  RM = 'RM',
  LM = 'LM',
  RW = 'RW',
  LW = 'LW',
  SS = 'SS',
  CF = 'CF',
  ST = 'ST'
}
