/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.878Z
 * Do not edit this file manually
 */

export enum PostTypeCode {
  Event = 'Event',
  Media = 'Media',
  Poll = 'Poll',
  Shared = 'Shared',
  Text = 'Text'
}
