/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.879Z
 * Do not edit this file manually
 */

export enum SocialLinkPlatform {
  Unknown = 'Unknown',
  Website = 'Website',
  LinkedIn = 'LinkedIn',
  GitHub = 'GitHub',
  Twitter = 'Twitter',
  Facebook = 'Facebook',
  Instagram = 'Instagram',
  YouTube = 'YouTube',
  TikTok = 'TikTok',
  Discord = 'Discord',
  WhatsApp = 'WhatsApp'
}
