/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.881Z
 * Do not edit this file manually
 */

export enum TeamLevelCode {
  U12 = 'U12',
  U15 = 'U15',
  U17 = 'U17',
  SENIOR = 'SENIOR'
}
