/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.882Z
 * Do not edit this file manually
 */

export enum UserPermissionCode {
  CreateSystem = 'CreateSystem',
  ReadSystem = 'ReadSystem',
  UpdateSystem = 'UpdateSystem',
  DeleteSystem = 'DeleteSystem',
  CreateUser = 'CreateUser',
  ReadUser = 'ReadUser',
  UpdateUser = 'UpdateUser',
  DeleteUser = 'DeleteUser',
  CreateFederation = 'CreateFederation',
  ReadFederation = 'ReadFederation',
  UpdateFederation = 'UpdateFederation',
  DeleteFederation = 'DeleteFederation',
  CreateCompetition = 'CreateCompetition',
  ReadCompetition = 'ReadCompetition',
  UpdateCompetition = 'UpdateCompetition',
  DeleteCompetition = 'DeleteCompetition',
  CreateClub = 'CreateClub',
  ReadClub = 'ReadClub',
  UpdateClub = 'UpdateClub',
  DeleteClub = 'DeleteClub',
  CreateTeam = 'CreateTeam',
  ReadTeam = 'ReadTeam',
  UpdateTeam = 'UpdateTeam',
  DeleteTeam = 'DeleteTeam',
  CreateMatch = 'CreateMatch',
  ReadMatch = 'ReadMatch',
  UpdateMatch = 'UpdateMatch',
  DeleteMatch = 'DeleteMatch',
  CreateContent = 'CreateContent',
  ReadContent = 'ReadContent',
  UpdateContent = 'UpdateContent',
  DeleteContent = 'DeleteContent'
}
