/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.882Z
 * Do not edit this file manually
 */

export enum UserRoleCode {
  General = 'General',
  Player = 'Player',
  Official = 'Official',
  Administrator = 'Administrator',
  Owner = 'Owner',
  System = 'System'
}
