import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.808Z
 * Do not edit this file manually
 */

export interface AdministratorDto extends UserDto {

}

export interface CreateAdministratorDto {

}

export interface UpdateAdministratorDto {

}
