import type { BillingAccountTypeCode } from '../enums/billingAccountTypeCode';
import type { OrganizationDto } from './organizationDto';
import type { UserDto } from './userDto';
import type { PaymentMethodDto } from './paymentMethodDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.813Z
 * Do not edit this file manually
 */

export interface BillingAccountDto {
  id: number;
  type: BillingAccountTypeCode;
  organizationId: number | null;
  organization: OrganizationDto | null;
  userId: number | null;
  user: UserDto | null;
  currency: string;
  country: string;
  externalCustomerId: string | null;
  createdAt: string;
  updatedAt: string | null;
  paymentMethods: PaymentMethodDto[];
}
