/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.814Z
 * Do not edit this file manually
 */

export interface CardAwardedDto {
  id: number;
  playerAwardedId: number;
  playerAwarded: Player;
}
