import type { ClubDto } from './clubDto';
import type { StadiumDto } from './stadiumDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.815Z
 * Do not edit this file manually
 */

export interface ClubStadiumLinkDto {
  id: number;
  clubId: number;
  club: ClubDto;
  stadiumId: number;
  stadium: StadiumDto;
}
