import type { OrganizationCreateDto, OrganizationDto } from './organizationDto';
import type { TeamDto } from './teamDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.815Z
 * Do not edit this file manually
 */

export interface ClubDto extends OrganizationDto {
  teams: TeamDto[];
}

export interface ClubCreateDto extends OrganizationCreateDto {
  email: string;
  province: string;
  description: string;
  city: string;
}
