import type { SubscriptionPlanDto } from './subscriptionPlanDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.816Z
 * Do not edit this file manually
 */

export interface ClubSubscriptionPlanDto extends SubscriptionPlanDto {

}
