import type { CommentDto } from './commentDto';
import type { CommentUserLikeLinkDto } from './commentUserLikeLinkDto';
import type { CommentCreateDto } from './commentCreateDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.819Z
 * Do not edit this file manually
 */

export interface CommentReplyDto extends CommentDto {
  commentId: string;
  comment: CommentDto;
  commentUserLikeLinks: CommentUserLikeLinkDto[];
  commentReplies: CommentReplyDto[];
  likesCount: number;
  commentsCount: number;
}

export interface CommentReplyCreateDto extends CommentCreateDto {
  commentId: string;
}
