import type { CommentDto } from './commentDto';
import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.820Z
 * Do not edit this file manually
 */

export interface CommentUserLikeLinkDto {
  id: string;
  commentId: string;
  comment: CommentDto;
  userId: string;
  user: UserDto;
  createdAt: string;
}
