import type { UserDto } from './userDto';
import type { CommentUserLikeLinkDto } from './commentUserLikeLinkDto';
import type { CommentReplyDto } from './commentReplyDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.818Z
 * Do not edit this file manually
 */

export interface CommentDto {
  id: string;
  userId: string;
  user: UserDto;
  content: string;
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string | null;
  commentUserLikeLinks: CommentUserLikeLinkDto[];
  commentReplies: CommentReplyDto[];
  isUpdated: boolean;
  likesCount: number;
  repliesCount: number;
  isLikedByCurrentUser: boolean;
  isOwnedByCurrentUser: boolean;
}
