import type { FederationDto } from './federationDto';
import type { CompetitionTypeCode } from '../enums/competitionTypeCode';
import type { CompetitionStatusCode } from '../enums/competitionStatusCode';
import type { TeamDto } from './teamDto';
import type { TeamCompetitionLinkDto } from './teamCompetitionLinkDto';
import type { FixtureDto } from './fixtureDto';
import type { MatchDto } from './matchDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.821Z
 * Do not edit this file manually
 */

export interface CompetitionDto {
  id: number;
  federationId: number;
  federation: FederationDto;
  name: string;
  nameAbbreviation: string | null;
  season: string;
  typeCode: CompetitionTypeCode;
  statusCode: CompetitionStatusCode;
  startDate: string;
  endDate: string | null;
  discriminator: string | null;
  winnerId: number | null;
  winner: TeamDto | null;
  createdAt: string;
  updatedAt: string | null;
  teamCompetitionLinks: TeamCompetitionLinkDto[];
  fixtures: FixtureDto[];
  matchRecords: MatchDto[];
}

export interface CompetitionCreateDto {
  federationId: number;
  season: string;
}
