import type { PostCreateDto, PostDto } from './postDto';
import type { VenueDto } from './venueDto';
import type { EventPostType } from '../enums/eventPostType';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.823Z
 * Do not edit this file manually
 */

export interface EventPostDto extends PostDto {
  name: string;
  description: string | null;
  maxAttendees: number;
  startAt: string | null;
  endAt: string | null;
  venueId: number | null;
  venue: VenueDto | null;
  coverImageId: number | null;
  coverImageUrl: string | null;
}

export interface EventPostCreateDto extends PostCreateDto {
  eventName: string;
  description: string;
  startAt: string;
  endAt: string;
  location: string;
  eventType: EventPostType;
  coverImage: File;
  requiresRSVP: boolean;
  maxAttendees: number;
  isPublic: boolean;
}
