import type { SubscriptionTierDto } from './subscriptionTierDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.827Z
 * Do not edit this file manually
 */

export interface FederationSubscriptionTierDto extends SubscriptionTierDto {

}
