import type { FederationDto } from './federationDto';
import type { ClubDto } from './clubDto';
import type { FederationMembershipStatus } from '../enums/federationMembershipStatus';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.824Z
 * Do not edit this file manually
 */

export interface FederationClubLinkDto {
  id: number;
  federationId: number;
  federation: FederationDto;
  clubId: number;
  club: ClubDto;
  status: FederationMembershipStatus;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
