import type { OrganizationCreateDto, OrganizationDto } from './organizationDto';
import type { CompetitionDto } from './competitionDto';
import type { FederationClubLinkDto } from './federationClubLinkDto';
import type { FederationClubMembershipApplicationDto } from './federationClubMembershipApplicationDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.825Z
 * Do not edit this file manually
 */

export interface FederationDto extends OrganizationDto {
  competitions: CompetitionDto[];
  federationClubLinks: FederationClubLinkDto[];
  federationClubMembershipApplications: FederationClubMembershipApplicationDto[];
}

export interface FederationCreateDto extends OrganizationCreateDto {

}
