import type { FederationMembershipStatus } from '../enums/federationMembershipStatus';
import type { FederationDto } from './federationDto';
import type { ClubDto } from './clubDto';
import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.825Z
 * Do not edit this file manually
 */

export interface FederationClubMembershipApplicationDto {
  id: number;
  status: FederationMembershipStatus;
  federationId: number;
  federation: FederationDto;
  clubId: number;
  club: ClubDto;
  reviewerId: number;
  reviewer: UserDto;
  reviewDate: string;
  createdAt: string;
  updatedAt: string;
}
