import type { MediaTypeCode } from '../enums/mediaTypeCode';
import type { MediaContext } from '../enums/mediaContext';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.828Z
 * Do not edit this file manually
 */

export interface FileMetadataDto {
  id: number;
  name: string;
  downloadUrl: string;
  viewUrl: string | null;
  caption: string | null;
  altText: string | null;
  type: MediaTypeCode;
  context: MediaContext;
  displayOrder: number;
  width: number | null;
  height: number | null;
  createdAt: string;
  updatedAt: string | null;
}
