/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.828Z
 * Do not edit this file manually
 */

export interface FixtureDto {
  id: number;
  homeTeamId: string;
  awayTeamId: string;
  venue: string;
  date: string;
  matchDay: number;
  cupRoundId: string | null;
  createdAt: string;
  updatedAt: string | null;
}

export interface FixtureCreateDto {
  teamId1: number;
  teamId2: number;
}
