/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.829Z
 * Do not edit this file manually
 */

export interface FolloweeDto {
  id: number;
  discriminator: string;
  firstName: string | null;
  lastName: string | null;
  name: string | null;
  avatar: string | null;
  logo: string | null;
}

export interface FollowerDto {
  id: number;
  discriminator: string;
  firstName: string | null;
  lastName: string | null;
  name: string | null;
  avatar: string | null;
  logo: string | null;
}

export interface FollowLinkDto {
  id: number;
  follower: FollowerDto;
  followee: FolloweeDto;
  createdAt: string;
}
