import type { PlayerDto } from './playerDto';
import type { MatchEventGoalLinkDto } from './matchEventGoalLinkDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.830Z
 * Do not edit this file manually
 */

export interface GoalDto {
  id: number;
  playerId: number;
  player: PlayerDto;
  assistPlayerId: number;
  assistPlayer: PlayerDto;
  matchEventGoalLinks: MatchEventGoalLinkDto[];
}
