import type { PostCreateDto, PostDto } from './postDto';
import type { FileMetadataDto } from './fileMetadataDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.832Z
 * Do not edit this file manually
 */

export interface ImagePostDto extends PostDto {
  caption: string | null;
  fileMetadatas: FileMetadataDto[];
}

export interface ImagesPostCreateDto extends PostCreateDto {
  caption: string;
  images: File[];
}
