import type { JurisdictionLevelCode } from '../enums/jurisdictionLevelCode';
import type { OrganizationDto } from './organizationDto';
import type { TeamDto } from './teamDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.833Z
 * Do not edit this file manually
 */

export interface JurisdictionDto {
  id: number;
  levelCode: JurisdictionLevelCode;
  createdAt: string;
  updatedAt: string | null;
  organizations: OrganizationDto[];
  teams: TeamDto[];
}
