import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.834Z
 * Do not edit this file manually
 */

export interface LikeDto {
  id: number;
  userId: number;
  user: UserDto;
  createdAt: string;
  discriminator: string | null;
}
