import type { PlayerDto } from './playerDto';
import type { PlayerPositionDto } from './playerPositionDto';
import type { LineUpPlayerLinkStatusCode } from '../enums/lineUpPlayerLinkStatusCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.835Z
 * Do not edit this file manually
 */

export interface LineUpPlayerLinkDto {
  id: number;
  lineUpId: number;
  lineUp: LineUpDto;
  playerId: number;
  player: PlayerDto;
  playerPositionId: number | null;
  playerPosition: PlayerPositionDto | null;
  statusCode: LineUpPlayerLinkStatusCode;
}
