import type { CompetitionDto } from './competitionDto';
import type { TeamDto } from './teamDto';
import type { StadiumDto } from './stadiumDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.835Z
 * Do not edit this file manually
 */

export interface MatchDto {
  id: number;
  discriminator: string;
  competitionId: number;
  competition: CompetitionDto;
  homeTeamId: number;
  homeTeam: TeamDto;
  awayTeamId: number;
  awayTeam: TeamDto;
  stadiumId: number;
  stadium: StadiumDto;
  matchDay: number;
  matchEvents: MatchEvent[];
  createdAt: string;
  updatedAt: string | null;
}

export interface MatchCreateDto {

}
