import type { MatchDto } from './matchDto';
import type { TeamDto } from './teamDto';
import type { GoalDto } from './goalDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.836Z
 * Do not edit this file manually
 */

export interface MatchEventDto {
  id: number;
  matchId: number;
  match: MatchDto;
  teamId: number | null;
  team: TeamDto | null;
  goalId: number | null;
  goal: GoalDto | null;
  timestamp: string;
  duration: TimeSpan;
}
