import type { MatchEventDto } from './matchEventDto';
import type { GoalDto } from './goalDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.836Z
 * Do not edit this file manually
 */

export interface MatchEventGoalLinkDto {
  matchEventId: number;
  matchEvent: MatchEventDto;
  goalId: number;
  goal: GoalDto;
}
