import type { MediaTypeCode } from '../enums/mediaTypeCode';
import type { MediaContext } from '../enums/mediaContext';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.837Z
 * Do not edit this file manually
 */

export interface MediaDto {
  id: number;
  fileName: string;
  downloadUrl: string;
  viewUrl: string | null;
  caption: string | null;
  altText: string | null;
  type: MediaTypeCode;
  context: MediaContext;
  displayOrder: number;
  extension: string;
  mimeType: string | null;
  fileSizeBytes: number | null;
  width: number | null;
  height: number | null;
  durationSeconds: number | null;
  ownerId: number | null;
  ownerType: string | null;
  createdAt: string;
  updatedAt: string;
}
