import type { PostDto } from './postDto';
import type { MediaDto } from './mediaDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.838Z
 * Do not edit this file manually
 */

export interface MediaPostDto extends PostDto {
  caption: string | null;
  media: MediaDto[];
}
