import type { JurisdictionDto } from './jurisdictionDto';
import type { OrganizationPersonaDto } from './organizationPersonaDto';
import type { SubscriptionPlanDto } from './subscriptionPlanDto';
import type { OrganizationTypeCode } from '../enums/organizationTypeCode';
import type { BillingAccountDto } from './billingAccountDto';
import type { PhysicalAddressCreateDto } from './physicalAddressDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.838Z
 * Do not edit this file manually
 */

export interface OrganizationDto {
  id: number;
  jurisdictionId: number;
  jurisdiction: JurisdictionDto;
  personaId: number;
  persona: OrganizationPersonaDto;
  subscriptionPlanId: number;
  subscriptionPlan: SubscriptionPlanDto;
  name: string;
  nameIdentifier: string;
  nameAbbreviation: string | null;
  logoUrl: string | null;
  bannerUrl: string | null;
  type: OrganizationTypeCode;
  yearEstablished: number | null;
  discriminator: string | null;
  billingAccounts: BillingAccountDto[];
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export interface OrganizationCreateDto {
  name: string;
  nameAbbreviation: string | null;
  jurisdictionId: number;
  yearEstablished: number;
  phoneNumber: string;
  physicalAddressCreate: PhysicalAddressCreateDto;
}
