import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.839Z
 * Do not edit this file manually
 */

export interface OrganizationPersonaDto extends UserDto {

}
