/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.843Z
 * Do not edit this file manually
 */

export interface PaymentMethodDto {
  id: number;
  billingAccountId: string;
  paymentProvider: string;
  externalPaymentMetthodId: string | null;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string | null;
}
