/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.844Z
 * Do not edit this file manually
 */

export interface PhysicalAddressDto {
  id: number;
  street: string;
  surbub: string;
  city: string;
  zip: string;
  province: string | null;
  country: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface PhysicalAddressCreateDto {
  street: string;
  surbub: string;
  city: string;
  zip: string;
  province: string | null;
  country: string | null;
}

export interface PhysicalAddressUpdateDto {
  street: string | null;
  surbub: string | null;
  city: string | null;
  zip: string | null;
  province: string | null;
  country: string | null;
}
