import type { PlayerDto } from './playerDto';
import type { TeamDto } from './teamDto';
import type { PlayerTeamStatusCode } from '../enums/playerTeamStatusCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.847Z
 * Do not edit this file manually
 */

export interface PlayerTeamLinkDto {
  id: number;
  playerId: number;
  player: PlayerDto;
  teamId: number;
  team: TeamDto;
  statusCode: PlayerTeamStatusCode;
  createdAt: string;
  updatedAt: string | null;
}
