import type { PlayerDto } from './playerDto';
import type { PlayerPositionDto } from './playerPositionDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.846Z
 * Do not edit this file manually
 */

export interface PlayerPositionLinkDto {
  id: number;
  playerId: number;
  player: PlayerDto;
  playerPositionId: number;
  playerPosition: PlayerPositionDto;
  proficience: number;
  isPrimary: boolean;
  createdAt: string;
  updatedAt: string | null;
}
