import type { PlayerPositionGroupCode } from '../enums/playerPositionGroupCode';
import type { PlayerPositionDto } from './playerPositionDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.846Z
 * Do not edit this file manually
 */

export interface PlayerPositionGroupDto {
  id: number;
  name: string;
  shortName: string;
  positionGroupCode: PlayerPositionGroupCode;
  displayOrder: number;
  createdAt: string;
  updatedAt: string | null;
  playerPositions: PlayerPositionDto[];
}
