import type { UserCreateDto, UserDto } from './userDto';
import type { PlayerPreferredFootCode } from '../enums/playerPreferredFootCode';
import type { PlayerTeamLinkDto } from './playerTeamLinkDto';
import type { PlayerPositionLinkDto } from './playerPositionLinkDto';
import type { PlayerSquadLinkDto } from './playerSquadLinkDto';
import type { LineUpPlayerLinkDto } from './lineUpPlayerLinkDto';
import type { GoalDto } from './goalDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.844Z
 * Do not edit this file manually
 */

export interface PlayerDto extends UserDto {
  jerseyNumber: number;
  height: number;
  weight: number;
  preferredFootCode: PlayerPreferredFootCode;
  nationality: string;
  playerTeamLinks: PlayerTeamLinkDto[];
  playerPositionsLinks: PlayerPositionLinkDto[];
  playerSquadLinks: PlayerSquadLinkDto[];
  lineUpPlayerLinks: LineUpPlayerLinkDto[];
  goals: GoalDto[];
  appearancesCount: number;
  goalsCount: number;
  assistsCount: number;
}

export interface PlayerCreateDto extends UserCreateDto {

}
