import type { PlayerPositionCode } from '../enums/playerPositionCode';
import type { PlayerPositionGroupDto } from './playerPositionGroupDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.845Z
 * Do not edit this file manually
 */

export interface PlayerPositionDto {
  id: number;
  name: string;
  shortName: string;
  positionCode: PlayerPositionCode;
  displayOrder: number;
  playerPositionGroupId: number;
  playerPositionGroup: PlayerPositionGroupDto;
  createdAt: string;
  updatedAt: string | null;
}

export interface PlayerPositionCreateDto {
  name: string;
  shortName: string;
}
