import type { PlayerDto } from './playerDto';
import type { SquadDto } from './squadDto';
import type { PlayerPositionCode } from '../enums/playerPositionCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.847Z
 * Do not edit this file manually
 */

export interface PlayerSquadLinkDto {
  id: number;
  playerId: number;
  player: PlayerDto;
  squadId: number;
  squad: SquadDto;
  positionCode: PlayerPositionCode;
  isDeleted: boolean;
  createdAt: string;
}
