import type { PollOptionDto } from './pollOptionDto';
import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.850Z
 * Do not edit this file manually
 */

export interface PollOptionUserLinkDto {
  id: string;
  pollOptionId: string;
  pollOption: PollOptionDto;
  userId: string;
  user: UserDto;
  createdAt: string;
  updatedAt: string | null;
  avatar: string | null;
  firstName: string;
  lastName: string;
  email: string;
}

export interface PollOptionUserLinkCreateDto {
  pollOptionId: string;
}
