import type { PollDto } from './pollDto';
import type { PollOptionUserLinkDto } from './pollOptionUserLinkDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.849Z
 * Do not edit this file manually
 */

export interface PollOptionDto {
  id: string;
  pollId: string;
  poll: PollDto;
  content: string;
  displayOrder: number;
  imageUrl: string | null;
  voteCount: number;
  votePercentage: number;
  isVotedByCurrentUser: boolean;
  pollOptionUserLinks: PollOptionUserLinkDto[];
  createdAt: string;
}

export interface PollOptionCreateDto {
  content: string;
}
