import type { PostCreateDto, PostDto } from './postDto';
import type { PollDto } from './pollDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.850Z
 * Do not edit this file manually
 */

export interface PollPostDto extends PostDto {
  pollId: number;
  poll: PollDto;
}

export interface PollPostCreateDto extends PostCreateDto {
  question: string;
  options: string[];
  allowMultipleChoice: boolean;
  expiresAt: string | null;
}
