import type { PollOptionDto } from './pollOptionDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.848Z
 * Do not edit this file manually
 */

export interface PollDto {
  id: string;
  question: string;
  allowMultipleChoice: boolean;
  expiresAt: string | null;
  createdAt: string;
  updatedAt: string | null;
  pollOptions: PollOptionDto[];
}

export interface PollCreateDto {
  question: string | null;
  allowMultipleChoice: boolean;
}
