import type { PostCommentDto } from './postCommentDto';
import type { UserDto } from './userDto';
import type { CommentReplyLikeDto } from './commentReplyLikeDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.852Z
 * Do not edit this file manually
 */

export interface PostCommentReplyDto {
  id: number;
  postCommentId: number;
  postComment: PostCommentDto;
  userId: number;
  user: UserDto;
  content: string;
  mentionedUserId: number | null;
  mentionedUser: UserDto | null;
  isDeleted: boolean;
  commentReplyLikes: CommentReplyLikeDto[];
  hashTags: HashTag[];
  createdAt: string;
  updatedAt: string | null;
  likesCount: number;
}
