import type { UserDto } from './userDto';
import type { PostTypeCode } from '../enums/postTypeCode';
import type { PostVisibilityCode } from '../enums/postVisibilityCode';
import type { PostCommentDto } from './postCommentDto';
import type { UserPostLikeLinkDto } from './userPostLikeLinkDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.853Z
 * Do not edit this file manually
 */

export interface PostDto {
  id: string;
  userId: string;
  user: UserDto | null;
  isAnonymous: boolean;
  organizationId: string | null;
  content: string | null;
  typeCode: PostTypeCode;
  visibility: PostVisibilityCode;
  name: string | null;
  description: string | null;
  maxAttendees: number;
  startAt: string | null;
  endAt: string | null;
  physicalAddressId: number | null;
  question: string | null;
  expiresAt: string | null;
  allowMultipleChoice: boolean;
  likesCount: number;
  commentsCount: number;
  sharesCount: number;
  viewsCount: number;
  isLikedByCurrentUser: boolean;
  isDeleted: boolean;
  isPinned: boolean;
  isEdited: boolean;
  discriminator: string;
  createdAt: string;
  updatedAt: string | null;
  postComments: PostCommentDto[];
  userPostLikeLinks: UserPostLikeLinkDto[];
}

export interface PostCreateDto {
  userId: string;
  postType: PostTypeCode;
  postVisibility: PostVisibilityCode;
  enableComments: boolean;
  enableShares: boolean;
}
