import type { PostCommentDto } from './postCommentDto';
import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.851Z
 * Do not edit this file manually
 */

export interface PostCommentLikeDto {
  id: number;
  postCommentId: number;
  postComment: PostCommentDto;
  userId: number;
  user: UserDto;
  createdAt: string;
}
