import type { CommentDto } from './commentDto';
import type { PostDto } from './postDto';
import type { CommentCreateDto } from './commentCreateDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.851Z
 * Do not edit this file manually
 */

export interface PostCommentDto extends CommentDto {
  postId: number;
  post: PostDto;
}

export interface PostCommentCreateDto extends CommentCreateDto {
  postId: string;
}
