import type { PostCreateDto, PostDto } from './postDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.854Z
 * Do not edit this file manually
 */

export interface SharedPostDto extends PostDto {
  originalPostId: number;
  originalPost: PostDto | null;
}

export interface SharedPostCreateDto extends PostCreateDto {

}
