import type { UserDto } from './userDto';
import type { SocialLinkPlatform } from '../enums/socialLinkPlatform';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.854Z
 * Do not edit this file manually
 */

export interface SocialLinkDto {
  id: number;
  userId: number;
  user: UserDto;
  link: string;
  platform: SocialLinkPlatform;
  createdAt: string;
  updatedAt: string;
}

export interface SocialLinkCreateDto {
  id: number;
  userId: number;
  user: UserDto;
  link: string;
  platform: SocialLinkPlatform;
  createdAt: string;
  updatedAt: string;
}
