import type { TeamDto } from './teamDto';
import type { PlayerSquadLinkDto } from './playerSquadLinkDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.855Z
 * Do not edit this file manually
 */

export interface SquadDto {
  id: number;
  name: string;
  teamId: number;
  team: TeamDto;
  playerSquadLinks: PlayerSquadLinkDto[];
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string | null;
}
