import type { PhysicalAddressDto } from './physicalAddressDto';
import type { ClubStadiumLinkDto } from './clubStadiumLinkDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.856Z
 * Do not edit this file manually
 */

export interface StadiumDto {
  id: number;
  name: string;
  capacity: number | null;
  isDeleted: boolean;
  physicalAddressId: number;
  physicalAddress: PhysicalAddressDto;
  clubStadiumLinks: ClubStadiumLinkDto[];
  createdAt: string;
  updatedAt: string | null;
}
