import type { SubscriptionTierDto } from './subscriptionTierDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.858Z
 * Do not edit this file manually
 */

export interface SubscriptionTierFeatureDto {
  id: string;
  subscriptionTierId: string;
  subscriptionTier: SubscriptionTierDto;
  name: string;
  description: string;
  isEnabled: boolean;
  createdAt: string;
  updatedAt: string | null;
}
