import type { BillingCycleCode } from '../enums/billingCycleCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.856Z
 * Do not edit this file manually
 */

export interface SubscriptionDto {
  id: string;
  name: string;
  subscriptionTierId: string;
  subscriptionTier: SubscriptionTier;
  price: number;
  billingCycle: BillingCycleCode;
  currency: string;
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string | null;
}
