import type { BillingCycleCode } from '../enums/billingCycleCode';
import type { SubscriptionTierDto } from './subscriptionTierDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.857Z
 * Do not edit this file manually
 */

export interface SubscriptionPlanDto {
  id: string;
  name: string;
  price: number;
  billingCycle: BillingCycleCode;
  description: string | null;
  subscriptionTierId: string;
  subscriptionTierDto: SubscriptionTierDto;
  discriminator: string;
  createdAt: string;
  updatedAt: string | null;
}
