import type { TierLevelCode } from '../enums/tierLevelCode';
import type { SubscriptionTierFeatureDto } from './subscriptionTierFeatureDto';
import type { SubscriptionPlanDto } from './subscriptionPlanDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.857Z
 * Do not edit this file manually
 */

export interface SubscriptionTierDto {
  id: string;
  name: string;
  callToActionText: string;
  description: string;
  level: TierLevelCode;
  discriminator: string;
  createAt: string;
  updatedAt: string | null;
  subscriptionTierFeatures: SubscriptionTierFeatureDto[];
  subscriptionPlans: SubscriptionPlanDto[];
}
