import type { ClubDto } from './clubDto';
import type { JurisdictionDto } from './jurisdictionDto';
import type { GenderCode } from '../enums/genderCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.859Z
 * Do not edit this file manually
 */

export interface TeamDto {
  id: number;
  name: string;
  nameAbbreviation: string;
  nickname: string | null;
  logoUrl: string | null;
  bannerUrl: string | null;
  clubId: number;
  club: ClubDto;
  jurisdictionId: number;
  jurisdiction: JurisdictionDto;
  gender: GenderCode;
  isDeleted: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export interface TeamCreateDto {
  clubId: string;
  name: string;
  nameAbbreviation: string;
  nickName: string | null;
  gender: GenderCode;
}
