import type { TeamDto } from './teamDto';
import type { CompetitionDto } from './competitionDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.859Z
 * Do not edit this file manually
 */

export interface TeamCompetitionLinkDto {
  id: number;
  teamId: number;
  team: TeamDto;
  competitionId: number;
  competition: CompetitionDto;
  createAt: string;
  updatedAt: string | null;
}
