import type { SubscriptionPlanDto } from './subscriptionPlanDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.860Z
 * Do not edit this file manually
 */

export interface TenantDto {
  id: number;
  name: string;
  nameIdentifier: string;
  personaId: string;
  subscriptionPlanId: string;
  subscriptionPlan: SubscriptionPlanDto;
  createdAt: string;
  updatedAt: string;
}

export interface TenantCreateDto {
  name: string;
}
