import type { PostCreateDto, PostDto } from './postDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.860Z
 * Do not edit this file manually
 */

export interface TextPostDto extends PostDto {

}

export interface TextPostCreateDto extends PostCreateDto {
  content: string;
}
