import type { ApplicationUserDto } from './Identity/applicationUserDto';
import type { GenderCode } from '../enums/genderCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.862Z
 * Do not edit this file manually
 */

export interface UserDto extends ApplicationUserDto {

}

export interface UserCreateDto {
  firstName: string;
  lastName: string;
  userName: string | null;
  email: string;
  phoneNumber: string | null;
  password: string;
  confirmPassword: string;
  gender: GenderCode;
  dateOfBirth: string | null;
  acceptTerms: boolean;
}

export interface UserUpdateDto {

}

export interface UserIdOrUserNameDto {
  userId: string | null;
  userName: string | null;
}

export interface UserIdAndUserNameDto {
  userId: string;
  userName: string;
}
