import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.861Z
 * Do not edit this file manually
 */

export interface UserActivityDto {
  id: number;
  userId: string;
  user: UserDto | null;
  name: string;
  description: string | null;
  userRoles: string[];
  timestamp: string;
}
