import type { PostDto } from './postDto';
import type { UserDto } from './userDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.863Z
 * Do not edit this file manually
 */

export interface UserPostLikeLinkDto {
  id: number;
  postId: number;
  post: PostDto;
  userId: number;
  user: UserDto;
  createdAt: string;
}
