import type { PhysicalAddressDto } from './physicalAddressDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.863Z
 * Do not edit this file manually
 */

export interface VenueDto {
  id: number;
  name: string;
  description: string | null;
  physicalAddressId: string | null;
  physicalAddress: PhysicalAddressDto | null;
  createdAt: string;
  updatedAt: string | null;
}
