import type { PostCreateDto, PostDto } from './postDto';
import type { FileMetadataDto } from './fileMetadataDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.864Z
 * Do not edit this file manually
 */

export interface VideoPostDto extends PostDto {
  caption: string | null;
  fileMetadatas: FileMetadataDto[];
}

export interface VideoPostCreateDto extends PostCreateDto {
  caption: string;
  videos: File[];
}
