import type { CardAwardedDto } from './cardAwardedDto';
import type { PlayerDto } from './playerDto';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.865Z
 * Do not edit this file manually
 */

export interface YellowCardDto extends CardAwardedDto {
  playerId: number;
  playerAwarded: PlayerDto;
  cardAwardedEventId: number;
  cardAwardedEvent: CardAwardedDto;
}
