/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.808Z
 * Do not edit this file manually
 */

export interface ApiResponse {
  success: boolean;
  message: string;
  errors: string[] | null;
  timestamp: string;
}
