/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.809Z
 * Do not edit this file manually
 */

export interface GenericApiResponse<T> {
  success: boolean;
  message: string;
  data: T | null;
  errors: string[] | null;
  timestamp: string;
}
