import type { GenericApiResponse } from './genericApiResponse';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.810Z
 * Do not edit this file manually
 */

export interface PagedGenericApiResponse<T> extends GenericApiResponse<T> {
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  totalRecords: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
