import type { ApiResponse } from './apiResponse';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.809Z
 * Do not edit this file manually
 */

export interface PagedApiResponse extends ApiResponse {
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  totalRecords: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
