import type { AuthUser } from './authUser';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.811Z
 * Do not edit this file manually
 */

export interface AuthResponse {
  tenantId: string | null;
  accessToken: string;
  refreshToken: string;
  user: AuthUser;
}
