/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.812Z
 * Do not edit this file manually
 */

export interface AuthUser {
  id: string;
  email: string;
  userName: string;
  firstName: string;
  middleName: string | null;
  lastName: string;
  avatar: string | null;
  coverImageUrl: string | null;
  isVerified: boolean;
  roles: string[];
  permissions: string[];
  discriminator: string | null;
}
