/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.812Z
 * Do not edit this file manually
 */

export interface LoginDto {
  username: string;
  password: string;
  rememberMe: boolean;
}
