/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.823Z
 * Do not edit this file manually
 */

export interface EmailVerificationResendDto {
  userId: string | null;
  userName: string;
  returnUrl: string;
}
