/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.822Z
 * Do not edit this file manually
 */

export interface EmailVerificationDto {
  userId: string;
  userName: string | null;
  token: string | null;
  otp: string | null;
  returnUrl: string;
}
