// tests/intergration/real.project.test.ts
import { beforeAll, describe, expect, it } from "vitest";
import * as fs from 'fs'
import * as path from 'path'
import { generate } from "../../src/core/index.ts";
import config from "../config/typesharp.config.ts";

const CONFIG_PATH = path.resolve(__dirname, '../config/typesharp.config.ts')
describe('TypeSharp - Real Project Integration', () => {

    // ─── Generation ───────────────────────────────────────────────────────────
    describe('Generation', () => {
        it('runs without throwing', async () => {
            await expect(generate(CONFIG_PATH)).resolves.not.toThrow()
        })

        it('creates the output directory', () => {
            expect(fs.existsSync(config.outputPath)).toBe(true)
        })

        it('generates at least one .ts file', () => {
            const files = getAllFiles(config.outputPath).filter(f => f.endsWith('.ts'))
            expect(files.length).toBeGreaterThan(0)
        })
    })


    // ─── File content ─────────────────────────────────────────────────────────
    describe('Generated file content', () => {
        it('every generated file has the TypeSharp header', () => {
            const files = getAllFiles(config.outputPath).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).toContain('Auto-generated by TypeSharp')
            }
        })

        it('every generated file has at least one export', () => {
            const files = getAllFiles(config.outputPath).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).toMatch(/export (interface|enum)/)
            }
        })

        it('no generated file contains raw C# types', () => {
            const csharpTypes = ['List<', 'IEnumerable<', 'Dictionary<', 'IFormFile ', 'Guid ', 'DateTime ']
            const files = getAllFiles(config.outputPath).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                for (const csharpType of csharpTypes) {
                    expect(content).not.toContain(csharpType)
                }
            }
        })
    })

    // ─── Known DTOs ───────────────────────────────────────────────────────────
    describe('Known DTOs', () => {
        it('generates User', () => {
            const file = findFileContaining(config.outputPath, 'User')
            expect(file).not.toBeNull()
        })

        it('Developer extends Employee', () => {
            const file = findFileContaining(config.outputPath, 'Employee')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('extends Employee')
        })

        it('generates User output file with correct fields', () => {
            const file = findFileContaining(config.outputPath, 'User')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('id')
            expect(content).toContain('name')
            expect(content).toContain('email')
        })

        it('generates User (stacked attributes)', () => {
            const file = findFileContaining(config.outputPath, 'User')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('id')
            expect(content).toContain('name')
        })

        it('generates UserRoleCode enum', () => {
            const file = findFileContaining(config.outputPath, 'UserRoleCode')
            expect(file).not.toBeNull()
        })

        it('generates Department with Guid mapped to string', () => {
            const file = findFileContaining(config.outputPath, 'Department')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('id')
            expect(content).not.toMatch(/:\s*Guid/)
            expect(content).toContain('string')
        })
        
        it('generates LegalInformationCreateDto', () => {
            const file = findFileContaining(config.outputPath, 'LegalInformationCreateDto')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('registrationNumber')
            expect(content).toContain('vatNumber')
            expect(content).toContain('| null')
        })
        
        it('OrganizationLegalInformationCreateDto extends LegalInformationCreateDto', () => {
            const file = findFileContaining(config.outputPath, 'OrganizationLegalInformationCreateDto')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('extends LegalInformationCreateDto')
        })
        
        it('OrganizationLegalInformationCreateDto has IFormFile mapped to File', () => {
            const file = findFileContaining(config.outputPath, 'OrganizationLegalInformationCreateDto')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('constitutionDocument: File')
            expect(content).toContain('proofOfRegistrationDocument: File')
        })
        
        it('generates ApiResponse<T> with generic parameter', () => {
            const file = findFileContaining(config.outputPath, 'ApiResponse')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('ApiResponse<T>')
            expect(content).toContain('success: boolean')
            expect(content).toContain('message: string | null')
            expect(content).toContain('data: T')
            expect(content).toContain('errors: string[]')
        })
        
        it('generates Employee with primitive properties', () => {
            const file = findFileContaining(config.outputPath, 'export interface Employee')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('id: number')
            expect(content).toContain('department: string')
        })

        it('deprecated properties have @deprecated JSDoc comment', () => {
            const file = findFileContaining(config.outputPath, 'export interface Employee');
            if (!file) return;
            const content = fs.readFileSync(file, 'utf-8');
            expect(content).toContain('@deprecated');
          });
    })

    // ─── Type correctness ─────────────────────────────────────────────────────
    describe('Type correctness', () => {
        it('nullable properties have | null', () => {
            const file = findFileContaining(config.outputPath, 'User')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')

            expect(content).toMatch(/name.*null/)
            expect(content).toMatch(/dateOfBirth.*null/)
        })

        it('no raw Guid type — should be string', () => {
            const files = getAllFiles(config.outputPath).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).not.toMatch(/:\s*Guid/)
            }
        })

        it('no raw DateTime type — should be string or Date', () => {
            const files = getAllFiles(config.outputPath).filter(f => f.endsWith('.ts'))

            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).not.toMatch(/:\s*DateTime/)
            }
        })

        it('ICollection<UserRoleCode> on User.Roles maps to UserRoleCode[]', () => {
            const file = findFileContaining(config.outputPath, 'roles')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toMatch(/roles.*UserRoleCode\[\]/)
        })
        
        it('ICollection<string> on User.Permissions maps to string[]', () => {
            const file = findFileContaining(config.outputPath, 'permissions')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toMatch(/permissions.*string\[\]/)
        })
        
        it('DateOnly? maps to string | null', () => {
            const file = findFileContaining(config.outputPath, 'User')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toMatch(/dateOfBirth.*string \| null/)
        })
        
        it('OrganizationLegalInformationCreateDto imports LegalInformationCreateDto', () => {
            const file = findFileContaining(config.outputPath, 'OrganizationLegalInformationCreateDto')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain("import type { LegalInformationCreateDto }")
        })
    })
})


// ─── Helpers ──────────────────────────────────────────────────────────────────

function getAllFiles(dir: string): string[] {
    if (!fs.existsSync(dir)) return []
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    return entries.flatMap(entry => {
        const fullPath = path.join(dir, entry.name)
        return entry.isDirectory() ? getAllFiles(fullPath) : [fullPath]
    })
}

function findFileContaining(dir: string, text: string): string | null {
    const files = getAllFiles(dir).filter(f => f.endsWith('.ts'))
    return files.find(f => fs.readFileSync(f, 'utf-8').includes(text)) ?? null
}