/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-04-07T12:42:11.591Z
 * Do not edit this file manually
 */

export interface ApiResponse<T> {
  success: boolean;
  message: string | null;
  data: T;
  errors: string[];
}
