/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-05T23:31:17.060Z
 * Do not edit this file manually
 */

export interface ApiResponse<T> {
  success: boolean;
  message: string | null;
  data: T;
  errors: string[];
}
