/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-21T06:18:06.053Z
 * Do not edit this file manually
 */

export interface ApiResponse<T> {
  success: boolean;
  message: string | null;
  data: T;
  errors: string[];
}
