import type { Employee } from './employee';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-04-11T03:37:11.891Z
 * Do not edit this file manually
 */

export interface Developer extends Employee {
  specialization: string;
}
