import type { Employee } from './employee';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-04-07T10:41:35.964Z
 * Do not edit this file manually
 */

export interface Developer extends Employee {
  specialization: string;
}
