import type { Employee } from './employee';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-23T08:59:10.624Z
 * Do not edit this file manually
 */

export interface Developer extends Employee {
  specialization: string;
}
