/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-21T10:05:25.519Z
 * Do not edit this file manually
 */

export interface Employee {
  id: number;
  /** @deprecated Use Department instead. */
  departmentName: string | null;
  department: string;
  /** @deprecated */
  legacyCode: string | null;
}
