/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-04-07T10:41:35.965Z
 * Do not edit this file manually
 */

export interface Employee {
  id: number;
  /** @deprecated Use Department instead. */
  departmentName: string | null;
  department: string;
  /** @deprecated */
  legacyCode: string | null;
}
