import type { UserRoleCode } from './user_role_code';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-04-07T12:42:11.596Z
 * Do not edit this file manually
 */

export interface User {
  id: number;
  name: string | null;
  dateOfBirth: string | null;
  email: string;
  roles: UserRoleCode[];
  permissions: string[];
  createdAt: string;
}
