import type { UserRoleCode } from './user_role_code';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-11T08:08:02.895Z
 * Do not edit this file manually
 */

export interface User {
  id: number;
  name: string | null;
  dateOfBirth: string | null;
  email: string;
  roles: UserRoleCode[];
  permissions: string[];
  createdAt: string;
}
