import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { generate } from '../../src/core'
import * as fs from 'fs'
import * as path from 'path'

const OUTPUT_DIR = path.resolve(__dirname, '../generated')
const CONFIG_PATH = path.resolve(__dirname, '../../typesharp.config.json')

describe('TypeSharp - Real Project Integration', () => {

    beforeAll(async () => {
        // Clean output before each run
        if (fs.existsSync(OUTPUT_DIR)) {
            fs.rmSync(OUTPUT_DIR, { recursive: true, force: true })
        }
    })

    // ─── Generation ───────────────────────────────────────────────────────────

    describe('Generation', () => {
        it('runs without throwing', async () => {
            await expect(generate(CONFIG_PATH)).resolves.not.toThrow()
        })

        it('creates the output directory', () => {
            expect(fs.existsSync(OUTPUT_DIR)).toBe(true)
        })

        it('generates at least one .ts file', () => {
            const files = getAllFiles(OUTPUT_DIR).filter(f => f.endsWith('.ts'))
            expect(files.length).toBeGreaterThan(0)
        })
    })

    // ─── File content ─────────────────────────────────────────────────────────

    describe('Generated file content', () => {
        it('every generated file has the TypeSharp header', () => {
            const files = getAllFiles(OUTPUT_DIR).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).toContain('Auto-generated by TypeSharp')
            }
        })

        it('every generated file has at least one export', () => {
            const files = getAllFiles(OUTPUT_DIR).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).toMatch(/export (interface|enum)/)
            }
        })

        it('no generated file contains raw C# types', () => {
            const csharpTypes = ['List<', 'IEnumerable<', 'Dictionary<', 'IFormFile ', 'Guid ', 'DateTime ']
            const files = getAllFiles(OUTPUT_DIR).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                for (const csharpType of csharpTypes) {
                    expect(content).not.toContain(csharpType)
                }
            }
        })
    })

    // ─── Known DTOs ───────────────────────────────────────────────────────────

    describe('Known DTOs', () => {
        it('generates UserDto', () => {
            const file = findFileContaining(OUTPUT_DIR, 'UserDto')
            expect(file).not.toBeNull()
        })

        it('UserDto extends ApplicationUserDto', () => {
            const file = findFileContaining(OUTPUT_DIR, 'UserDto')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('extends ApplicationUserDto')
        })

        it('generates UserCreateDto with correct fields', () => {
            const file = findFileContaining(OUTPUT_DIR, 'UserCreateDto')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('firstName')
            expect(content).toContain('lastName')
            expect(content).toContain('email')
            expect(content).toContain('password')
            expect(content).toContain('gender')
            expect(content).toContain('acceptTerms')
        })

        it('generates UserIdOrUserNameDto (stacked attributes)', () => {
            const file = findFileContaining(OUTPUT_DIR, 'UserIdOrUserNameDto')
            expect(file).not.toBeNull()
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            expect(content).toContain('userId')
            expect(content).toContain('userName')
        })

        it('generates GenderCode enum', () => {
            const file = findFileContaining(OUTPUT_DIR, 'GenderCode')
            expect(file).not.toBeNull()
        })
    })

    // ─── Type correctness ─────────────────────────────────────────────────────

    describe('Type correctness', () => {
        it('nullable properties have | null', () => {
            const file = findFileContaining(OUTPUT_DIR, 'UserCreateDto')
            if (!file) return
            const content = fs.readFileSync(file, 'utf-8')
            // userName and phoneNumber are nullable in UserCreateDto
            expect(content).toMatch(/userName.*null/)
            expect(content).toMatch(/phoneNumber.*null/)
        })

        it('no raw Guid type — should be string', () => {
            const files = getAllFiles(OUTPUT_DIR).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).not.toMatch(/:\s*Guid/)
            }
        })

        it('no raw DateTime type — should be string', () => {
            const files = getAllFiles(OUTPUT_DIR).filter(f => f.endsWith('.ts'))
            for (const file of files) {
                const content = fs.readFileSync(file, 'utf-8')
                expect(content).not.toMatch(/:\s*DateTime/)
            }
        })
    })
})

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getAllFiles(dir: string): string[] {
    if (!fs.existsSync(dir)) return []
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    return entries.flatMap(entry => {
        const fullPath = path.join(dir, entry.name)
        return entry.isDirectory() ? getAllFiles(fullPath) : [fullPath]
    })
}

function findFileContaining(dir: string, text: string): string | null {
    const files = getAllFiles(dir).filter(f => f.endsWith('.ts'))
    return files.find(f => fs.readFileSync(f, 'utf-8').includes(text)) ?? null
}