import type { GenderCode } from '../../enums/genderCode';

/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.806Z
 * Do not edit this file manually
 */

export interface RegisterUserDto {
  firstName: string;
  lastName: string;
  userName: string | null;
  email: string;
  phoneNumber: string | null;
  password: string;
  confirmPassword: string;
  gender: GenderCode;
  dateOfBirth: string | null;
  acceptTerms: boolean;
  returnUrl: string | null;
}
