/**
 * Auto-generated by TypeSharp
 * Generated at: 2026-03-01T09:13:05.807Z
 * Do not edit this file manually
 */

export interface ResendEmailConfirmationDto {
  userId: string;
  email: string;
  returnUrl: string | null;
}
